version: '3'

services:
  jira:
    image: atlassian/jira-software
    ports:
      - "8080:8080"
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://postgres:5432/jiradb
      - ATL_JDBC_USER=jira
      - ATL_JDBC_PASSWORD=jirapass
      - ATL_DB_DRIVER=org.postgresql.Driver
    volumes:
      - jira_data:/var/atlassian/application-data/jira
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=jira
      - POSTGRES_PASSWORD=jirapass
      - POSTGRES_DB=jiradb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

volumes:
  jira_data:
  postgres_data: