---
- name: Install required software on frontend and backend containers
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install nginx on frontend container
      when: inventory_hostname == "frontend_container"
      apt:
        name: nginx
        state: present

    - name: Install Python and pip on backend container
      when: inventory_hostname == "backend_container"
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Docker on both frontend and backend containers
      apt:
        name: docker.io
        state: present
      when: inventory_hostname in ["frontend_container", "backend_container"]

    - name: Install Python dependencies on backend container
      when: inventory_hostname == "backend_container"
      pip:
        name: flask
        state: present
