version: '3'

services:
  jira:
    image: atlassian/jira-software
    ports:
      - "80:8080"
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://${POSTGRES_HOST}/jiradb
      - ATL_JDBC_USER=jira
      - ATL_JDBC_PASSWORD=${DB_PASSWORD}
      - ATL_DB_DRIVER=org.postgresql.Driver
      - JIRA_ADMIN_PASSWORD=${JIRA_ADMIN_PASSWORD}
      - JVM_MINIMUM_MEMORY=384m
      - JVM_MAXIMUM_MEMORY=768m
    volumes:
      - jira_data:/var/atlassian/application-data/jira
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 900M
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  jira_data: