version: '3.8'

services:
  jira:
    image: atlassian/jira-software
    container_name: jira
    ports:
      - "80:8080"
    environment:
      - JVM_MINIMUM_MEMORY=384m
      - JVM_MAXIMUM_MEMORY=768m
      - JIRA_ADMIN_PASSWORD=${JIRA_ADMIN_PASSWORD}
      - ATL_DB_TYPE=postgresql
      - ATL_DB_DRIVER=org.postgresql.Driver
      - ATL_JDBC_URL=jdbc:postgresql://${POSTGRES_HOST}:5432/jiradb
      - ATL_JDBC_USER=jira
      - ATL_JDBC_PASSWORD=${DB_PASSWORD}
    volumes:
      - jira_data:/var/atlassian/application-data/jira
    restart: unless-stopped

volumes:
  jira_data:
    name: jira_data